//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace lenguaje.Recursos_Localizables {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class StringResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringResources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("lenguaje.Recursos_Localizables.StringResources", typeof(StringResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a tchjam archivoe.
        /// </summary>
        internal static string archivoAbrir {
            get {
                return ResourceManager.GetString("archivoAbrir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a nak´o archivoe.
        /// </summary>
        internal static string archivoGuardar {
            get {
                return ResourceManager.GetString("archivoGuardar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a lok´an ta archivoe.
        /// </summary>
        internal static string archivoSalir {
            get {
                return ResourceManager.GetString("archivoSalir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a lo´ktao edicione.
        /// </summary>
        internal static string edicionCopiar {
            get {
                return ResourceManager.GetString("edicionCopiar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a k´oko edicione.
        /// </summary>
        internal static string edicionCortar {
            get {
                return ResourceManager.GetString("edicionCortar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a nap´o edicione.
        /// </summary>
        internal static string edicionPegar {
            get {
                return ResourceManager.GetString("edicionPegar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Español.
        /// </summary>
        internal static string lenguajeEspañol {
            get {
                return ResourceManager.GetString("lenguajeEspañol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Francés.
        /// </summary>
        internal static string lenguajeFrances {
            get {
                return ResourceManager.GetString("lenguajeFrances", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Inglés.
        /// </summary>
        internal static string lenguajeIngles {
            get {
                return ResourceManager.GetString("lenguajeIngles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tzotzil.
        /// </summary>
        internal static string lenguajeTzotzil {
            get {
                return ResourceManager.GetString("lenguajeTzotzil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a menu Archivoetike.
        /// </summary>
        internal static string menuArchivo {
            get {
                return ResourceManager.GetString("menuArchivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a menu edicione.
        /// </summary>
        internal static string menuEdicion {
            get {
                return ResourceManager.GetString("menuEdicion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a menu k´opetik.
        /// </summary>
        internal static string menuLenguaje {
            get {
                return ResourceManager.GetString("menuLenguaje", resourceCulture);
            }
        }
    }
}
